export default {
    
    USER_FETCH_PROFILE_START: 'USER_FETCH_PROFILE_START',
    USER_FETCH_PROFILE_SUCCESS: 'USER_FETCH_PROFILE_SUCCESS',
    USER_FETCH_PROFILE_ERROR: 'USER_FETCH_PROFILE_ERROR',
    
 } 